'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace soapMoodle
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="soapMoodle.wsMoodleSoap")>  _
    Public Interface wsMoodleSoap
        
        'CODEGEN: Generating message contract since message HelloWorldRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld(ByVal request As soapMoodle.HelloWorldRequest) As soapMoodle.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As soapMoodle.HelloWorldRequest) As System.Threading.Tasks.Task(Of soapMoodle.HelloWorldResponse)
        
        'CODEGEN: Generating message contract since message GetActivitiesRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetActivities", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetActivities(ByVal request As soapMoodle.GetActivitiesRequest) As soapMoodle.GetActivitiesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetActivities", ReplyAction:="*")>  _
        Function GetActivitiesAsync(ByVal request As soapMoodle.GetActivitiesRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesResponse)
        
        'CODEGEN: Generating message contract since message GetActivitiesGradeRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetActivitiesGrade", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetActivitiesGrade(ByVal request As soapMoodle.GetActivitiesGradeRequest) As soapMoodle.GetActivitiesGradeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetActivitiesGrade", ReplyAction:="*")>  _
        Function GetActivitiesGradeAsync(ByVal request As soapMoodle.GetActivitiesGradeRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesGradeResponse)
        
        'CODEGEN: Generating message contract since message GetStudentsFromCourseRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetStudentsFromCourse", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetStudentsFromCourse(ByVal request As soapMoodle.GetStudentsFromCourseRequest) As soapMoodle.GetStudentsFromCourseResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetStudentsFromCourse", ReplyAction:="*")>  _
        Function GetStudentsFromCourseAsync(ByVal request As soapMoodle.GetStudentsFromCourseRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetStudentsFromCourseResponse)
        
        'CODEGEN: Generating message contract since message GetActivitiesFromCourseAndUserRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetActivitiesFromCourseAndUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetActivitiesFromCourseAndUser(ByVal request As soapMoodle.GetActivitiesFromCourseAndUserRequest) As soapMoodle.GetActivitiesFromCourseAndUserResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetActivitiesFromCourseAndUser", ReplyAction:="*")>  _
        Function GetActivitiesFromCourseAndUserAsync(ByVal request As soapMoodle.GetActivitiesFromCourseAndUserRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesFromCourseAndUserResponse)
        
        'CODEGEN: Generating message contract since message GetCourseByUserIdRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCourseByUserId", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCourseByUserId(ByVal request As soapMoodle.GetCourseByUserIdRequest) As soapMoodle.GetCourseByUserIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCourseByUserId", ReplyAction:="*")>  _
        Function GetCourseByUserIdAsync(ByVal request As soapMoodle.GetCourseByUserIdRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetCourseByUserIdResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AuthUser
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userNameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("UserName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("Password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
                Me.RaisePropertyChanged("AnyAttr")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class grade
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private itemidField As Long
        
        Private courseidField As Long
        
        Private itemnameField As String
        
        Private itemtypeField As String
        
        Private itemmoduleField As String
        
        Private instanceidField As Long
        
        Private grademaxField As Decimal
        
        Private grademinField As Decimal
        
        Private useridField As Long
        
        Private idnumberField As String
        
        Private rawgradeField As Decimal
        
        Private finalgradeField As Decimal
        
        Private feedbackField As String
        
        Private timecreatedField As Date
        
        Private timemodifiedField As Date
        
        Private aggregationstatusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property itemid() As Long
            Get
                Return Me.itemidField
            End Get
            Set
                Me.itemidField = value
                Me.RaisePropertyChanged("itemid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property courseid() As Long
            Get
                Return Me.courseidField
            End Get
            Set
                Me.courseidField = value
                Me.RaisePropertyChanged("courseid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property itemname() As String
            Get
                Return Me.itemnameField
            End Get
            Set
                Me.itemnameField = value
                Me.RaisePropertyChanged("itemname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property itemtype() As String
            Get
                Return Me.itemtypeField
            End Get
            Set
                Me.itemtypeField = value
                Me.RaisePropertyChanged("itemtype")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property itemmodule() As String
            Get
                Return Me.itemmoduleField
            End Get
            Set
                Me.itemmoduleField = value
                Me.RaisePropertyChanged("itemmodule")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property instanceid() As Long
            Get
                Return Me.instanceidField
            End Get
            Set
                Me.instanceidField = value
                Me.RaisePropertyChanged("instanceid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property grademax() As Decimal
            Get
                Return Me.grademaxField
            End Get
            Set
                Me.grademaxField = value
                Me.RaisePropertyChanged("grademax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property grademin() As Decimal
            Get
                Return Me.grademinField
            End Get
            Set
                Me.grademinField = value
                Me.RaisePropertyChanged("grademin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property userid() As Long
            Get
                Return Me.useridField
            End Get
            Set
                Me.useridField = value
                Me.RaisePropertyChanged("userid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property idnumber() As String
            Get
                Return Me.idnumberField
            End Get
            Set
                Me.idnumberField = value
                Me.RaisePropertyChanged("idnumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property rawgrade() As Decimal
            Get
                Return Me.rawgradeField
            End Get
            Set
                Me.rawgradeField = value
                Me.RaisePropertyChanged("rawgrade")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property finalgrade() As Decimal
            Get
                Return Me.finalgradeField
            End Get
            Set
                Me.finalgradeField = value
                Me.RaisePropertyChanged("finalgrade")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property feedback() As String
            Get
                Return Me.feedbackField
            End Get
            Set
                Me.feedbackField = value
                Me.RaisePropertyChanged("feedback")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property timecreated() As Date
            Get
                Return Me.timecreatedField
            End Get
            Set
                Me.timecreatedField = value
                Me.RaisePropertyChanged("timecreated")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property timemodified() As Date
            Get
                Return Me.timemodifiedField
            End Get
            Set
                Me.timemodifiedField = value
                Me.RaisePropertyChanged("timemodified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property aggregationstatus() As String
            Get
                Return Me.aggregationstatusField
            End Get
            Set
                Me.aggregationstatusField = value
                Me.RaisePropertyChanged("aggregationstatus")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class activity
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private courseidField As Long
        
        Private course_nameField As String
        
        Private moduleIdField As Long
        
        Private module_nameField As String
        
        Private instanceField As Long
        
        Private instance_nameField As String
        
        Private date_addField As Date
        
        Private visibleField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property courseid() As Long
            Get
                Return Me.courseidField
            End Get
            Set
                Me.courseidField = value
                Me.RaisePropertyChanged("courseid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property course_name() As String
            Get
                Return Me.course_nameField
            End Get
            Set
                Me.course_nameField = value
                Me.RaisePropertyChanged("course_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property moduleId() As Long
            Get
                Return Me.moduleIdField
            End Get
            Set
                Me.moduleIdField = value
                Me.RaisePropertyChanged("moduleId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property module_name() As String
            Get
                Return Me.module_nameField
            End Get
            Set
                Me.module_nameField = value
                Me.RaisePropertyChanged("module_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property instance() As Long
            Get
                Return Me.instanceField
            End Get
            Set
                Me.instanceField = value
                Me.RaisePropertyChanged("instance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property instance_name() As String
            Get
                Return Me.instance_nameField
            End Get
            Set
                Me.instance_nameField = value
                Me.RaisePropertyChanged("instance_name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property date_add() As Date
            Get
                Return Me.date_addField
            End Get
            Set
                Me.date_addField = value
                Me.RaisePropertyChanged("date_add")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property visible() As Boolean
            Get
                Return Me.visibleField
            End Get
            Set
                Me.visibleField = value
                Me.RaisePropertyChanged("visible")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="HelloWorld", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthUser As soapMoodle.AuthUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthUser As soapMoodle.AuthUser)
            MyBase.New
            Me.AuthUser = AuthUser
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="HelloWorldResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetActivities", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetActivitiesRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthUser As soapMoodle.AuthUser
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CourseId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Integer)
            MyBase.New
            Me.AuthUser = AuthUser
            Me.CourseId = CourseId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetActivitiesResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetActivitiesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetActivitiesResult() As soapMoodle.activity
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetActivitiesResult() As soapMoodle.activity)
            MyBase.New
            Me.GetActivitiesResult = GetActivitiesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetActivitiesGrade", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetActivitiesGradeRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthUser As soapMoodle.AuthUser
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CourseId As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public ItemModule As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public InstanceId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Long, ByVal ItemModule As String, ByVal InstanceId As Long)
            MyBase.New
            Me.AuthUser = AuthUser
            Me.CourseId = CourseId
            Me.ItemModule = ItemModule
            Me.InstanceId = InstanceId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetActivitiesGradeResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetActivitiesGradeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetActivitiesGradeResult() As soapMoodle.grade
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetActivitiesGradeResult() As soapMoodle.grade)
            MyBase.New
            Me.GetActivitiesGradeResult = GetActivitiesGradeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetStudentsFromCourse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetStudentsFromCourseRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthUser As soapMoodle.AuthUser
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public CourseId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Integer)
            MyBase.New
            Me.AuthUser = AuthUser
            Me.CourseId = CourseId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetStudentsFromCourseResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetStudentsFromCourseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetStudentsFromCourseResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetStudentsFromCourseResult As String)
            MyBase.New
            Me.GetStudentsFromCourseResult = GetStudentsFromCourseResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetActivitiesFromCourseAndUser", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetActivitiesFromCourseAndUserRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthUser As soapMoodle.AuthUser
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public categoryId As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public userId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthUser As soapMoodle.AuthUser, ByVal categoryId As Integer, ByVal userId As Integer)
            MyBase.New
            Me.AuthUser = AuthUser
            Me.categoryId = categoryId
            Me.userId = userId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetActivitiesFromCourseAndUserResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetActivitiesFromCourseAndUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetActivitiesFromCourseAndUserResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetActivitiesFromCourseAndUserResult As String)
            MyBase.New
            Me.GetActivitiesFromCourseAndUserResult = GetActivitiesFromCourseAndUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetCourseByUserId", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetCourseByUserIdRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public AuthUser As soapMoodle.AuthUser
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public userId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthUser As soapMoodle.AuthUser, ByVal userId As Integer)
            MyBase.New
            Me.AuthUser = AuthUser
            Me.userId = userId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetCourseByUserIdResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetCourseByUserIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public GetCourseByUserIdResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCourseByUserIdResult As String)
            MyBase.New
            Me.GetCourseByUserIdResult = GetCourseByUserIdResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsMoodleSoapChannel
        Inherits soapMoodle.wsMoodleSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsMoodleSoapClient
        Inherits System.ServiceModel.ClientBase(Of soapMoodle.wsMoodleSoap)
        Implements soapMoodle.wsMoodleSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_HelloWorld(ByVal request As soapMoodle.HelloWorldRequest) As soapMoodle.HelloWorldResponse Implements soapMoodle.wsMoodleSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld(ByVal AuthUser As soapMoodle.AuthUser) As String
            Dim inValue As soapMoodle.HelloWorldRequest = New soapMoodle.HelloWorldRequest()
            inValue.AuthUser = AuthUser
            Dim retVal As soapMoodle.HelloWorldResponse = CType(Me,soapMoodle.wsMoodleSoap).HelloWorld(inValue)
            Return retVal.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_HelloWorldAsync(ByVal request As soapMoodle.HelloWorldRequest) As System.Threading.Tasks.Task(Of soapMoodle.HelloWorldResponse) Implements soapMoodle.wsMoodleSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync(ByVal AuthUser As soapMoodle.AuthUser) As System.Threading.Tasks.Task(Of soapMoodle.HelloWorldResponse)
            Dim inValue As soapMoodle.HelloWorldRequest = New soapMoodle.HelloWorldRequest()
            inValue.AuthUser = AuthUser
            Return CType(Me,soapMoodle.wsMoodleSoap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetActivities(ByVal request As soapMoodle.GetActivitiesRequest) As soapMoodle.GetActivitiesResponse Implements soapMoodle.wsMoodleSoap.GetActivities
            Return MyBase.Channel.GetActivities(request)
        End Function
        
        Public Function GetActivities(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Integer) As soapMoodle.activity()
            Dim inValue As soapMoodle.GetActivitiesRequest = New soapMoodle.GetActivitiesRequest()
            inValue.AuthUser = AuthUser
            inValue.CourseId = CourseId
            Dim retVal As soapMoodle.GetActivitiesResponse = CType(Me,soapMoodle.wsMoodleSoap).GetActivities(inValue)
            Return retVal.GetActivitiesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetActivitiesAsync(ByVal request As soapMoodle.GetActivitiesRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesResponse) Implements soapMoodle.wsMoodleSoap.GetActivitiesAsync
            Return MyBase.Channel.GetActivitiesAsync(request)
        End Function
        
        Public Function GetActivitiesAsync(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Integer) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesResponse)
            Dim inValue As soapMoodle.GetActivitiesRequest = New soapMoodle.GetActivitiesRequest()
            inValue.AuthUser = AuthUser
            inValue.CourseId = CourseId
            Return CType(Me,soapMoodle.wsMoodleSoap).GetActivitiesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetActivitiesGrade(ByVal request As soapMoodle.GetActivitiesGradeRequest) As soapMoodle.GetActivitiesGradeResponse Implements soapMoodle.wsMoodleSoap.GetActivitiesGrade
            Return MyBase.Channel.GetActivitiesGrade(request)
        End Function
        
        Public Function GetActivitiesGrade(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Long, ByVal ItemModule As String, ByVal InstanceId As Long) As soapMoodle.grade()
            Dim inValue As soapMoodle.GetActivitiesGradeRequest = New soapMoodle.GetActivitiesGradeRequest()
            inValue.AuthUser = AuthUser
            inValue.CourseId = CourseId
            inValue.ItemModule = ItemModule
            inValue.InstanceId = InstanceId
            Dim retVal As soapMoodle.GetActivitiesGradeResponse = CType(Me,soapMoodle.wsMoodleSoap).GetActivitiesGrade(inValue)
            Return retVal.GetActivitiesGradeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetActivitiesGradeAsync(ByVal request As soapMoodle.GetActivitiesGradeRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesGradeResponse) Implements soapMoodle.wsMoodleSoap.GetActivitiesGradeAsync
            Return MyBase.Channel.GetActivitiesGradeAsync(request)
        End Function
        
        Public Function GetActivitiesGradeAsync(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Long, ByVal ItemModule As String, ByVal InstanceId As Long) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesGradeResponse)
            Dim inValue As soapMoodle.GetActivitiesGradeRequest = New soapMoodle.GetActivitiesGradeRequest()
            inValue.AuthUser = AuthUser
            inValue.CourseId = CourseId
            inValue.ItemModule = ItemModule
            inValue.InstanceId = InstanceId
            Return CType(Me,soapMoodle.wsMoodleSoap).GetActivitiesGradeAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetStudentsFromCourse(ByVal request As soapMoodle.GetStudentsFromCourseRequest) As soapMoodle.GetStudentsFromCourseResponse Implements soapMoodle.wsMoodleSoap.GetStudentsFromCourse
            Return MyBase.Channel.GetStudentsFromCourse(request)
        End Function
        
        Public Function GetStudentsFromCourse(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Integer) As String
            Dim inValue As soapMoodle.GetStudentsFromCourseRequest = New soapMoodle.GetStudentsFromCourseRequest()
            inValue.AuthUser = AuthUser
            inValue.CourseId = CourseId
            Dim retVal As soapMoodle.GetStudentsFromCourseResponse = CType(Me,soapMoodle.wsMoodleSoap).GetStudentsFromCourse(inValue)
            Return retVal.GetStudentsFromCourseResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetStudentsFromCourseAsync(ByVal request As soapMoodle.GetStudentsFromCourseRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetStudentsFromCourseResponse) Implements soapMoodle.wsMoodleSoap.GetStudentsFromCourseAsync
            Return MyBase.Channel.GetStudentsFromCourseAsync(request)
        End Function
        
        Public Function GetStudentsFromCourseAsync(ByVal AuthUser As soapMoodle.AuthUser, ByVal CourseId As Integer) As System.Threading.Tasks.Task(Of soapMoodle.GetStudentsFromCourseResponse)
            Dim inValue As soapMoodle.GetStudentsFromCourseRequest = New soapMoodle.GetStudentsFromCourseRequest()
            inValue.AuthUser = AuthUser
            inValue.CourseId = CourseId
            Return CType(Me,soapMoodle.wsMoodleSoap).GetStudentsFromCourseAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetActivitiesFromCourseAndUser(ByVal request As soapMoodle.GetActivitiesFromCourseAndUserRequest) As soapMoodle.GetActivitiesFromCourseAndUserResponse Implements soapMoodle.wsMoodleSoap.GetActivitiesFromCourseAndUser
            Return MyBase.Channel.GetActivitiesFromCourseAndUser(request)
        End Function
        
        Public Function GetActivitiesFromCourseAndUser(ByVal AuthUser As soapMoodle.AuthUser, ByVal categoryId As Integer, ByVal userId As Integer) As String
            Dim inValue As soapMoodle.GetActivitiesFromCourseAndUserRequest = New soapMoodle.GetActivitiesFromCourseAndUserRequest()
            inValue.AuthUser = AuthUser
            inValue.categoryId = categoryId
            inValue.userId = userId
            Dim retVal As soapMoodle.GetActivitiesFromCourseAndUserResponse = CType(Me,soapMoodle.wsMoodleSoap).GetActivitiesFromCourseAndUser(inValue)
            Return retVal.GetActivitiesFromCourseAndUserResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetActivitiesFromCourseAndUserAsync(ByVal request As soapMoodle.GetActivitiesFromCourseAndUserRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesFromCourseAndUserResponse) Implements soapMoodle.wsMoodleSoap.GetActivitiesFromCourseAndUserAsync
            Return MyBase.Channel.GetActivitiesFromCourseAndUserAsync(request)
        End Function
        
        Public Function GetActivitiesFromCourseAndUserAsync(ByVal AuthUser As soapMoodle.AuthUser, ByVal categoryId As Integer, ByVal userId As Integer) As System.Threading.Tasks.Task(Of soapMoodle.GetActivitiesFromCourseAndUserResponse)
            Dim inValue As soapMoodle.GetActivitiesFromCourseAndUserRequest = New soapMoodle.GetActivitiesFromCourseAndUserRequest()
            inValue.AuthUser = AuthUser
            inValue.categoryId = categoryId
            inValue.userId = userId
            Return CType(Me,soapMoodle.wsMoodleSoap).GetActivitiesFromCourseAndUserAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetCourseByUserId(ByVal request As soapMoodle.GetCourseByUserIdRequest) As soapMoodle.GetCourseByUserIdResponse Implements soapMoodle.wsMoodleSoap.GetCourseByUserId
            Return MyBase.Channel.GetCourseByUserId(request)
        End Function
        
        Public Function GetCourseByUserId(ByVal AuthUser As soapMoodle.AuthUser, ByVal userId As Integer) As String
            Dim inValue As soapMoodle.GetCourseByUserIdRequest = New soapMoodle.GetCourseByUserIdRequest()
            inValue.AuthUser = AuthUser
            inValue.userId = userId
            Dim retVal As soapMoodle.GetCourseByUserIdResponse = CType(Me,soapMoodle.wsMoodleSoap).GetCourseByUserId(inValue)
            Return retVal.GetCourseByUserIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function soapMoodle_wsMoodleSoap_GetCourseByUserIdAsync(ByVal request As soapMoodle.GetCourseByUserIdRequest) As System.Threading.Tasks.Task(Of soapMoodle.GetCourseByUserIdResponse) Implements soapMoodle.wsMoodleSoap.GetCourseByUserIdAsync
            Return MyBase.Channel.GetCourseByUserIdAsync(request)
        End Function
        
        Public Function GetCourseByUserIdAsync(ByVal AuthUser As soapMoodle.AuthUser, ByVal userId As Integer) As System.Threading.Tasks.Task(Of soapMoodle.GetCourseByUserIdResponse)
            Dim inValue As soapMoodle.GetCourseByUserIdRequest = New soapMoodle.GetCourseByUserIdRequest()
            inValue.AuthUser = AuthUser
            inValue.userId = userId
            Return CType(Me,soapMoodle.wsMoodleSoap).GetCourseByUserIdAsync(inValue)
        End Function
    End Class
End Namespace
