
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("dd93cb13-ee26-477c-8afc-240901332a43")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("academiaModel", "FK_evaluatest2_evaluatest1", "evaluatest1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(evaluatest1), "evaluatest2", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(evaluatest2), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class academiaEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new academiaEntities object using the connection string found in the 'academiaEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=academiaEntities", "academiaEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new academiaEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "academiaEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new academiaEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "academiaEntities")
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property evaluatest1() As ObjectSet(Of evaluatest1)
        Get
            If (_evaluatest1 Is Nothing) Then
                _evaluatest1 = MyBase.CreateObjectSet(Of evaluatest1)("evaluatest1")
            End If
            Return _evaluatest1
        End Get
    End Property

    Private _evaluatest1 As ObjectSet(Of evaluatest1)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property evaluatest2() As ObjectSet(Of evaluatest2)
        Get
            If (_evaluatest2 Is Nothing) Then
                _evaluatest2 = MyBase.CreateObjectSet(Of evaluatest2)("evaluatest2")
            End If
            Return _evaluatest2
        End Get
    End Property

    Private _evaluatest2 As ObjectSet(Of evaluatest2)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the evaluatest1 EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToevaluatest1(ByVal evaluatest1 As evaluatest1)
        MyBase.AddObject("evaluatest1", evaluatest1)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the evaluatest2 EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToevaluatest2(ByVal evaluatest2 As evaluatest2)
        MyBase.AddObject("evaluatest2", evaluatest2)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="academiaModel", Name:="evaluatest1")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class evaluatest1
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new evaluatest1 object.
    ''' </summary>
    ''' <param name="numtest">Initial value of the numtest property.</param>
    Public Shared Function Createevaluatest1(numtest As Global.System.Int32) As evaluatest1
        Dim evaluatest1 as evaluatest1 = New evaluatest1
        evaluatest1.numtest = numtest
        Return evaluatest1
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property empresa() As Nullable(Of Global.System.Int16)
        Get
            Return _empresa
        End Get
        Set
            OnempresaChanging(value)
            ReportPropertyChanging("empresa")
            _empresa = StructuralObject.SetValidValue(value, "empresa")
            ReportPropertyChanged("empresa")
            OnempresaChanged()
        End Set
    End Property

    Private _empresa As Nullable(Of Global.System.Int16)
    Private Partial Sub OnempresaChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnempresaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ciclo() As Nullable(Of Global.System.Int16)
        Get
            Return _ciclo
        End Get
        Set
            OncicloChanging(value)
            ReportPropertyChanging("ciclo")
            _ciclo = StructuralObject.SetValidValue(value, "ciclo")
            ReportPropertyChanged("ciclo")
            OncicloChanged()
        End Set
    End Property

    Private _ciclo As Nullable(Of Global.System.Int16)
    Private Partial Sub OncicloChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OncicloChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fecha() As Nullable(Of Global.System.DateTime)
        Get
            Return _fecha
        End Get
        Set
            OnfechaChanging(value)
            ReportPropertyChanging("fecha")
            _fecha = StructuralObject.SetValidValue(value, "fecha")
            ReportPropertyChanged("fecha")
            OnfechaChanged()
        End Set
    End Property

    Private _fecha As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnfechaChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnfechaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property tipotest() As Nullable(Of Global.System.Int16)
        Get
            Return _tipotest
        End Get
        Set
            OntipotestChanging(value)
            ReportPropertyChanging("tipotest")
            _tipotest = StructuralObject.SetValidValue(value, "tipotest")
            ReportPropertyChanged("tipotest")
            OntipotestChanged()
        End Set
    End Property

    Private _tipotest As Nullable(Of Global.System.Int16)
    Private Partial Sub OntipotestChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OntipotestChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property numtest() As Global.System.Int32
        Get
            Return _numtest
        End Get
        Set
            If (_numtest <> Value) Then
                OnnumtestChanging(value)
                ReportPropertyChanging("numtest")
                _numtest = StructuralObject.SetValidValue(value, "numtest")
                ReportPropertyChanged("numtest")
                OnnumtestChanged()
            End If
        End Set
    End Property

    Private _numtest As Global.System.Int32
    Private Partial Sub OnnumtestChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnnumtestChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property empleado() As Nullable(Of Global.System.Int32)
        Get
            Return _empleado
        End Get
        Set
            OnempleadoChanging(value)
            ReportPropertyChanging("empleado")
            _empleado = StructuralObject.SetValidValue(value, "empleado")
            ReportPropertyChanged("empleado")
            OnempleadoChanged()
        End Set
    End Property

    Private _empleado As Nullable(Of Global.System.Int32)
    Private Partial Sub OnempleadoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnempleadoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property contrato() As Nullable(Of Global.System.Int32)
        Get
            Return _contrato
        End Get
        Set
            OncontratoChanging(value)
            ReportPropertyChanging("contrato")
            _contrato = StructuralObject.SetValidValue(value, "contrato")
            ReportPropertyChanged("contrato")
            OncontratoChanged()
        End Set
    End Property

    Private _contrato As Nullable(Of Global.System.Int32)
    Private Partial Sub OncontratoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OncontratoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property codigo() As Nullable(Of Global.System.Int16)
        Get
            Return _codigo
        End Get
        Set
            OncodigoChanging(value)
            ReportPropertyChanging("codigo")
            _codigo = StructuralObject.SetValidValue(value, "codigo")
            ReportPropertyChanged("codigo")
            OncodigoChanged()
        End Set
    End Property

    Private _codigo As Nullable(Of Global.System.Int16)
    Private Partial Sub OncodigoChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OncodigoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property unidad() As Nullable(Of Global.System.Int16)
        Get
            Return _unidad
        End Get
        Set
            OnunidadChanging(value)
            ReportPropertyChanging("unidad")
            _unidad = StructuralObject.SetValidValue(value, "unidad")
            ReportPropertyChanged("unidad")
            OnunidadChanged()
        End Set
    End Property

    Private _unidad As Nullable(Of Global.System.Int16)
    Private Partial Sub OnunidadChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnunidadChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property estado() As Nullable(Of Global.System.Int16)
        Get
            Return _estado
        End Get
        Set
            OnestadoChanging(value)
            ReportPropertyChanging("estado")
            _estado = StructuralObject.SetValidValue(value, "estado")
            ReportPropertyChanged("estado")
            OnestadoChanged()
        End Set
    End Property

    Private _estado As Nullable(Of Global.System.Int16)
    Private Partial Sub OnestadoChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnestadoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fechae() As Nullable(Of Global.System.DateTime)
        Get
            Return _fechae
        End Get
        Set
            OnfechaeChanging(value)
            ReportPropertyChanging("fechae")
            _fechae = StructuralObject.SetValidValue(value, "fechae")
            ReportPropertyChanged("fechae")
            OnfechaeChanged()
        End Set
    End Property

    Private _fechae As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnfechaeChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnfechaeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property emevaluador() As Nullable(Of Global.System.Int32)
        Get
            Return _emevaluador
        End Get
        Set
            OnemevaluadorChanging(value)
            ReportPropertyChanging("emevaluador")
            _emevaluador = StructuralObject.SetValidValue(value, "emevaluador")
            ReportPropertyChanged("emevaluador")
            OnemevaluadorChanged()
        End Set
    End Property

    Private _emevaluador As Nullable(Of Global.System.Int32)
    Private Partial Sub OnemevaluadorChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnemevaluadorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property conevaluador() As Nullable(Of Global.System.Int32)
        Get
            Return _conevaluador
        End Get
        Set
            OnconevaluadorChanging(value)
            ReportPropertyChanging("conevaluador")
            _conevaluador = StructuralObject.SetValidValue(value, "conevaluador")
            ReportPropertyChanged("conevaluador")
            OnconevaluadorChanged()
        End Set
    End Property

    Private _conevaluador As Nullable(Of Global.System.Int32)
    Private Partial Sub OnconevaluadorChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnconevaluadorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property observa() As Global.System.String
        Get
            Return _observa
        End Get
        Set
            OnobservaChanging(value)
            ReportPropertyChanging("observa")
            _observa = StructuralObject.SetValidValue(value, true, "observa")
            ReportPropertyChanged("observa")
            OnobservaChanged()
        End Set
    End Property

    Private _observa As Global.System.String
    Private Partial Sub OnobservaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnobservaChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("academiaModel", "FK_evaluatest2_evaluatest1", "evaluatest2")>
     Public Property evaluatest2() As EntityCollection(Of evaluatest2)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of evaluatest2)("academiaModel.FK_evaluatest2_evaluatest1", "evaluatest2")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of evaluatest2)("academiaModel.FK_evaluatest2_evaluatest1", "evaluatest2", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="academiaModel", Name:="evaluatest2")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class evaluatest2
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new evaluatest2 object.
    ''' </summary>
    ''' <param name="empresa">Initial value of the empresa property.</param>
    ''' <param name="ciclo">Initial value of the ciclo property.</param>
    ''' <param name="tipotest">Initial value of the tipotest property.</param>
    ''' <param name="numtest">Initial value of the numtest property.</param>
    ''' <param name="numpregunta">Initial value of the numpregunta property.</param>
    Public Shared Function Createevaluatest2(empresa As Global.System.Int16, ciclo As Global.System.Int16, tipotest As Global.System.Int16, numtest As Global.System.Int32, numpregunta As Global.System.Int16) As evaluatest2
        Dim evaluatest2 as evaluatest2 = New evaluatest2
        evaluatest2.empresa = empresa
        evaluatest2.ciclo = ciclo
        evaluatest2.tipotest = tipotest
        evaluatest2.numtest = numtest
        evaluatest2.numpregunta = numpregunta
        Return evaluatest2
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa() As Global.System.Int16
        Get
            Return _empresa
        End Get
        Set
            If (_empresa <> Value) Then
                OnempresaChanging(value)
                ReportPropertyChanging("empresa")
                _empresa = StructuralObject.SetValidValue(value, "empresa")
                ReportPropertyChanged("empresa")
                OnempresaChanged()
            End If
        End Set
    End Property

    Private _empresa As Global.System.Int16
    Private Partial Sub OnempresaChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnempresaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ciclo() As Global.System.Int16
        Get
            Return _ciclo
        End Get
        Set
            If (_ciclo <> Value) Then
                OncicloChanging(value)
                ReportPropertyChanging("ciclo")
                _ciclo = StructuralObject.SetValidValue(value, "ciclo")
                ReportPropertyChanged("ciclo")
                OncicloChanged()
            End If
        End Set
    End Property

    Private _ciclo As Global.System.Int16
    Private Partial Sub OncicloChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OncicloChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property tipotest() As Global.System.Int16
        Get
            Return _tipotest
        End Get
        Set
            If (_tipotest <> Value) Then
                OntipotestChanging(value)
                ReportPropertyChanging("tipotest")
                _tipotest = StructuralObject.SetValidValue(value, "tipotest")
                ReportPropertyChanged("tipotest")
                OntipotestChanged()
            End If
        End Set
    End Property

    Private _tipotest As Global.System.Int16
    Private Partial Sub OntipotestChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OntipotestChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property numtest() As Global.System.Int32
        Get
            Return _numtest
        End Get
        Set
            If (_numtest <> Value) Then
                OnnumtestChanging(value)
                ReportPropertyChanging("numtest")
                _numtest = StructuralObject.SetValidValue(value, "numtest")
                ReportPropertyChanged("numtest")
                OnnumtestChanged()
            End If
        End Set
    End Property

    Private _numtest As Global.System.Int32
    Private Partial Sub OnnumtestChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnnumtestChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property area() As Nullable(Of Global.System.Int16)
        Get
            Return _area
        End Get
        Set
            OnareaChanging(value)
            ReportPropertyChanging("area")
            _area = StructuralObject.SetValidValue(value, "area")
            ReportPropertyChanged("area")
            OnareaChanged()
        End Set
    End Property

    Private _area As Nullable(Of Global.System.Int16)
    Private Partial Sub OnareaChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnareaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property numpregunta() As Global.System.Int16
        Get
            Return _numpregunta
        End Get
        Set
            If (_numpregunta <> Value) Then
                OnnumpreguntaChanging(value)
                ReportPropertyChanging("numpregunta")
                _numpregunta = StructuralObject.SetValidValue(value, "numpregunta")
                ReportPropertyChanged("numpregunta")
                OnnumpreguntaChanged()
            End If
        End Set
    End Property

    Private _numpregunta As Global.System.Int16
    Private Partial Sub OnnumpreguntaChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnnumpreguntaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property numopcion() As Nullable(Of Global.System.Int16)
        Get
            Return _numopcion
        End Get
        Set
            OnnumopcionChanging(value)
            ReportPropertyChanging("numopcion")
            _numopcion = StructuralObject.SetValidValue(value, "numopcion")
            ReportPropertyChanged("numopcion")
            OnnumopcionChanged()
        End Set
    End Property

    Private _numopcion As Nullable(Of Global.System.Int16)
    Private Partial Sub OnnumopcionChanging(value As Nullable(Of Global.System.Int16))
    End Sub

    Private Partial Sub OnnumopcionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("academiaModel", "FK_evaluatest2_evaluatest1", "evaluatest1")>
    Public Property evaluatest1() As evaluatest1
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of evaluatest1)("academiaModel.FK_evaluatest2_evaluatest1", "evaluatest1").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of evaluatest1)("academiaModel.FK_evaluatest2_evaluatest1", "evaluatest1").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property evaluatest1Reference() As EntityReference(Of evaluatest1)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of evaluatest1)("academiaModel.FK_evaluatest2_evaluatest1", "evaluatest1")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of evaluatest1)("academiaModel.FK_evaluatest2_evaluatest1", "evaluatest1", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region

